# -*- coding: utf-8 -*-
"""Imaz_type3_level1_problem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IwELv_jlkckA6FcenjOJX9CLOqCr0xho
"""

trow = [1]
list1=[]
y = [0]
i=0
n=int(input())
for x in range(max(n,0)):
  list1.append(trow)
  trow=[l+r for l,r in zip(trow+y, y+trow)]

print(list1)